/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Viwes;

import Controllers.ComandaController;
import Controllers.ProdutoController;
import Controllers.ProdutosComandaController;
import Models.Comandas;
import Models.Produtos;
import Models.TableModel;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author andre
 */
public class NovaComanda extends javax.swing.JFrame {

    private ProdutoController ProdutoControl = new ProdutoController();
    private static List<Produtos> listaDeProdutos = new ArrayList<>();
    private static TableModel modelo = new TableModel(listaDeProdutos);
    private   ComandaController Control = new ComandaController();
    /**
     * Creates new form NovaComanda
     */
    public NovaComanda() {
        initComponents();
        JTable tabela = new JTable(modelo);
        tabela.setFont(new Font("Arial", Font.PLAIN, 18));
        tabela.setShowVerticalLines(true);
        tabela.setShowHorizontalLines(true);
        tabela.setGridColor(Color.gray);
        // Adicione a tabela a um JScrollPane (opcional)
        jScrollPane1.setViewportView(tabela);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NovaComandaTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        NomeClienteInput = new javax.swing.JTextField();
        LabelNomeCliente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        InputNomeProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        InputCodigoProduto = new javax.swing.JTextField();
        PesquisarCodigoBtn = new javax.swing.JButton();
        PesquisarNomeBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        AbrirComandaBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        NovaComandaTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NovaComandaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NovaComandaTitulo.setText("Nova Comanda");

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabela);

        LabelNomeCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelNomeCliente.setText("Insira o nome do cliente:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Produtos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nome do produto");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Código do produto");

        PesquisarCodigoBtn.setText("Pesquisar com código");
        PesquisarCodigoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarCodigoBtnActionPerformed(evt);
            }
        });

        PesquisarNomeBtn.setText("Pesquisar por nome");
        PesquisarNomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarNomeBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Adicionar Produtos");

        AbrirComandaBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AbrirComandaBtn.setText("Abrir comanda");
        AbrirComandaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirComandaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NovaComandaTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 37, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(215, 215, 215)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                            .addComponent(PesquisarCodigoBtn)
                                            .addComponent(InputCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PesquisarNomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(InputNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(3, 3, 3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel5)
                                                            .addGap(142, 142, 142))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(LabelNomeCliente)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(NomeClienteInput, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(9, 9, 9)))))
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AbrirComandaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(190, 190, 190))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(NovaComandaTitulo)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNomeCliente)
                            .addComponent(NomeClienteInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(InputNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(PesquisarNomeBtn)
                        .addGap(25, 25, 25)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(InputCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(PesquisarCodigoBtn)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(AbrirComandaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        public static void adicionarProduto(Produtos produto, int Quantidade) {
        Produtos NovoProduto = new Produtos();
        NovoProduto.setCodigo(produto.getCodigo());
        NovoProduto.setNome(produto.getNome());
        NovoProduto.setUnidade(produto.getUnidade());
        NovoProduto.setPreco(produto.getPreco());
        NovoProduto.setQuantidadeDisponivel(produto.getQuantidadeDisponivel());
        NovoProduto.setDataUltimaVenda(produto.getDataUltimaVenda());
        NovoProduto.setQuantidade(Quantidade);

        listaDeProdutos.add(NovoProduto);
        modelo.fireTableDataChanged();

    }

    private static boolean existeNoCarrinho(Produtos produto) {
        for (Produtos produtoLista : listaDeProdutos) {
            if (produtoLista.getCodigo().equals(produto.getCodigo())) {
                System.out.println("Item já está no carrinho");
                return true;
            }
        }
        return false;
    }

    private void PesquisarNomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarNomeBtnActionPerformed

        try {
            String PesquisaPorNome = InputNomeProduto.getText();
            Produtos Produto = ProdutoControl.findProdutoByNome(PesquisaPorNome);
            JanelaAddProdutoComanda add = new JanelaAddProdutoComanda(Produto);
            add.setVisible(rootPaneCheckingEnabled);
            add.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            add.setLocationRelativeTo(this);
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(this, "Ocorreu um error ao adicionar produto.\nOu ele não pode ser encontrado\nDetalhes do error:\n\n" + Ex.getMessage(), "Ops! ocorreu um error", JOptionPane.YES_OPTION);
        }

    }//GEN-LAST:event_PesquisarNomeBtnActionPerformed

    private void PesquisarCodigoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarCodigoBtnActionPerformed

        try {
            String PesquisaCodigo = InputCodigoProduto.getText();

            int codigo = Integer.parseInt(PesquisaCodigo);
            Produtos Produto = ProdutoControl.findProdutoByCodigo(codigo);

            JanelaAddProdutoComanda add = new JanelaAddProdutoComanda(Produto);
            add.setVisible(rootPaneCheckingEnabled);
            add.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            add.setLocationRelativeTo(this);

        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(this, "Ocorreu um error ao adicionar produto.\nOu ele não pode ser encontrado\nDetalhes do error:\n\n" + Ex.getMessage(), "Ops! ocorreu um error", JOptionPane.YES_OPTION);
        }


    }//GEN-LAST:event_PesquisarCodigoBtnActionPerformed

    private void AbrirComandaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirComandaBtnActionPerformed
        // TODO add your handling code here:
      
    
        int codigo = Control.createOne(NomeClienteInput.getText());
    
        int id = Control.findIdByCodigo(codigo);
          
         ProdutosComandaController ProdutoControl = new ProdutosComandaController();
        
        ProdutoControl.createMany(listaDeProdutos, id);
           Comandas comanda = new Comandas();
           comanda.setNomeCliente(NomeClienteInput.getText());
           comanda.setStatus("aberto");
           comanda.setCodigo(codigo);
 
        Main.atualizarTabelaComandas(comanda);
        dispose();

    }//GEN-LAST:event_AbrirComandaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovaComanda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbrirComandaBtn;
    private javax.swing.JTextField InputCodigoProduto;
    private javax.swing.JTextField InputNomeProduto;
    private javax.swing.JLabel LabelNomeCliente;
    private javax.swing.JTextField NomeClienteInput;
    private javax.swing.JLabel NovaComandaTitulo;
    private javax.swing.JButton PesquisarCodigoBtn;
    private javax.swing.JButton PesquisarNomeBtn;
    private javax.swing.JTable Tabela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
